config/routes.rb
Yabe::Application.routes.draw do
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end
  resources :authors
  resources :sessions, :only => [:new, :create, :destroy]
  resources :tags, :only => [:index]

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  root :to => 'posts#index'

  get "pages/contact"
  get "pages/about"

end

app/models/author.rb
# == Schema Information
# Schema version: 20110104233042
#
# Table name: authors
#
#  id                 :integer         not null, primary key
#  name               :string(75)
#  email              :string(75)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(64)
#  salt               :string(64)
#  profile            :text
#  owner              :boolean
#

require 'digest'

class Author < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  has_many :posts, :dependent => :destroy

  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  validates :email, :presence => true,
                    :format => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..20 }
  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    author = find_by_email(email)
    return nil if author.nil?
    return author if author.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    author = find_by_id(id)
    (author && author.salt == cookie_salt) ? author : nil
  end

  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :authenticate, :except => [:show, :index]
  before_filter :correct_author, :only => [:edit, :update]
  before_filter :owner_only, :only => [:new, :create, :destroy]

  def new
    @author = Author.new
    @title = "New Author"
  end

  def create
    @author = Author.new(params[:author])
    if @author.save
      flash[:success] = "Welcome our new author!"
      redirect_to authors_path
    else
      @title = "New Author"
      @author.password = ""
      @author.password_confirmation = ""
      render :new
    end
  end

  def show
    @author = Author.find(params[:id])
    @title = @author.name
  end

  def edit 
    @title = "Profile"
  end

  def update
    @author.update_attributes(params[:author])
    if @author.save
      flash[:success] = "Your profile has been updated."
      redirect_to @author
    else
      @title = "Profile"
      @author.password = ""
      @author.password_confirmation = ""
      render :edit
    end
  end

  def index
    @title = "Authors"
    @authors = Author.paginate(:page => params[:page], :per_page => 10)
  end

  def destroy
    Author.find(params[:id]).destroy
    flash[:success] = "Author has been deleted."
    redirect_to authors_path
  end

  private
    def authenticate
      deny_access unless logged_in?
    end

    def correct_author
      @author = Author.find(params[:id])
      redirect_to root_path unless current_author?(@author)
    end

    def owner_only
      redirect_to(root_path) unless current_author.owner?
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<li>
  <%= gravatar_for author, :size => 50 %>
  <%= link_to author.name, author %>
  <% if current_author && current_author.owner? %>
   | <%= link_to "delete", author, :method => :delete,
                                   :confirm => "Are you sure you wish to delete this author?",
                                   :title => "Delete #{author.name}" %>
  <% end %>
</li>

app/views/authors/edit.html.erb
<%= form_for(@author) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @author %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/authors/index.html.erb
<h1>Authors</h1>

<%= will_paginate %>

<ul class="authors">
  <%= render @authors %>
</ul>

<%= will_paginate %>

app/views/authors/new.html.erb
<%= form_for(@author) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/authors/show.html.erb
<div class="profile">
  <div class="main">
    <h1>
      <%= gravatar_for @author %>
      <%= @author.name %>
    </h1>
  </div>
  <div class="sidebar round">
    <strong>Name</strong> <%= @author.name %><br/>
    <strong>URL</strong> <%= link_to author_path(@author), @author %>
  </div>
</div>