config/routes.rb
Yabe::Application.routes.draw do
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end
  resources :authors
  resources :sessions, :only => [:new, :create, :destroy]
  resources :tags, :only => [:index]

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  root :to => 'posts#index'

  get "pages/contact"
  get "pages/about"

end

app/models/post.rb
# == Schema Information
# Schema version: 20110606111155
#
# Table name: posts
#
#  id           :integer         not null, primary key
#  title        :string(75)
#  body         :text
#  created_at   :datetime
#  updated_at   :datetime
#  author_id    :integer
#  published_on :datetime
#  cached_slug  :string(255)
#  month        :integer
#  year         :integer
#

class Post < ActiveRecord::Base
  attr_accessible :title, :body, :published_on, :tag_tokens
  attr_reader :tag_tokens
  belongs_to :author
  has_many :comments, :dependent => :destroy
  has_and_belongs_to_many :tags, :uniq => true
  has_friendly_id :title, :use_slug => true

  validates :title, :presence => true,
                    :length => { :maximum => 75 }
  validates :body, :presence => true

  default_scope where('published_on <= :published', :published => 1.minute.from_now).order('published_on DESC')
  before_save :on_before_save

  def tag_tokens=(ids)
    ids.gsub!(/\[(.+?)\]/) { Tag.create!(:name => $1).id } 
    self.tag_ids = ids.split(',')
  end

  private 
    def on_before_save
      self.published_on ||= Time.now
      self.month = self.published_on.month
      self.year = self.published_on.year
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  before_filter :authenticate, :only => [:new, :edit, :create, :update, :destroy]
  before_filter :correct_author, :only => [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.xml
  def index
    @title = "Home"
    @posts = Post.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
      format.json { render :json => @posts }
      format.atom # index.atom.builder
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])
    @title = @post.title

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new
    @title = "New Post"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @title = @post.title
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = current_author.posts.build(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :flash => {:success => 'Post was successfully created.' } ) }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        @title = "New Post"
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])
    @title = @post.title

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :flash => { :success => 'Post was successfully updated.' } ) }
        format.xml  { head :ok }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end

  private 
    def authenticate
      redirect_to login_path unless logged_in?
    end

    def correct_author
      @post = Post.find(params[:id])
      unless can_edit_post?(@post)
        flash[:error] = "You cannot edit posts that do not belong to you."
        redirect_to @post
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_editor_links(post)
    return unless can_edit_post?(post)

    raw("<p>" + link_to('Edit', edit_post_path(post)) + ' | ' +
      link_to('Delete', post, :method => :delete, :confirm => "Are you sure?") +
      "</p>")
  end

  def can_edit_post?(post)
    logged_in? && 
      (current_author.owner? || current_author.id == post.author_id)
  end
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tag_tokens, "Tags" %>
    <%= f.text_field :tag_tokens, 'data-pre' => @post.tags.map(&:attributes).to_json %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= javascript_include_tag tags_path(:format => 'js') %>
<% end %>

app/views/posts/_post.html.erb
<article id="post_<%= post.id %>">
  <header>
    <h1><%= link_to_unless_current post.title, post %></h1>
  </header>
  <%= simple_format post.body %>
</article>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= will_paginate %>

<%= render @posts %>

<%= will_paginate %>

<br />

<%= link_to 'New Post', new_post_path if logged_in? %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render @post %>

<%= render_editor_links(@post) %>

<section id="metainfo">
  <div>
    <label>Written by</label>
    <span><%= @post.author.name %></span>
  </div>
  <div>
    <label>Created </label>
    <time datetime="<%= @post.created_at %>" title="<%= @post.created_at.localtime %>">
      <%= time_ago_in_words(@post.created_at) %> ago
    </time>
  </div>
  <div>
    <label>Published</label>
    <time datetime="<%= @post.published_on %>" title="<%= @post.published_on.localtime %>">
      <%= time_ago_in_words(@post.published_on) %> ago
    </time>
  </div>
  <div>
    <label>Tags:</label>
    <ul>
      <% @post.tags.each do |t| %>
        <li><%= t.name %></li>
      <% end %>
    </ul>
  </div>
</section>

<section id="comments">
  <header>
    <h1>Comments</h1>
  </header>
  <%= render @post.comments %>
  <footer>
    <%= render 'comments/form' %>
  </footer>
</section>