config/routes.rb
Yabe::Application.routes.draw do
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end
  resources :authors
  resources :sessions, :only => [:new, :create, :destroy]
  resources :tags, :only => [:index]

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  root :to => 'posts#index'

  get "pages/contact"
  get "pages/about"

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Authors", authors_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <% if logged_in? %>
    <nav class="round">
      <ul>
          <li><%= link_to "Profile", current_author %></li>
          <li><%= link_to "Logout", logout_path, :method => :delete %></li>
      </ul>
    </nav>
  <% end %>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults, 'jquery.tokeninput' %>
    <%= auto_discovery_link_tag :atom, posts_path(:format => :atom) %>
  </head>
  <body>
    <div class="container">
      <section class="flash">
        <% flash.each do |key, value| %>
          <div class="<%= key %>"><%= value %></div>
        <% end %>
      </section>
      <%= render 'layouts/header' %>   
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>